services:
  vite:
    build: .
    ports:
      - "5173:5173"  # Expose Vite dev server port
    volumes:
      - .:/app  # Mount current directory into the container
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    working_dir: /app  # Ensure the working directory is set properly

  playwright:
    build: 
      context: .
      dockerfile: Dockerfile.playwright
    ports:
      - "8083:8083"  # Expose server port
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - BASEURL=http://vite:5173/
    working_dir: /app  # Ensure the working directory is set properly
